plugins {
    id 'java'
}

group = 'com.agilesolutions'
version = '1.0.0-SNAPSHOT'

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://repo.spring.io/milestone' }
        maven { url = 'https://repo.spring.io/snapshot' }
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
    }
}