server:
  port: 8081

spring:
  application:
    name: trader-mcp-tools

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

  ai:
    mcp:
      server:
        name: trader-mcp-tools
        version: 1.0.0
        type: SYNC
        # By default, endpoints are at /sse and /mcp/message


twelvedata:
  api-key: ${TWELVEDATA_API_KEY}