spring:
  application:
    name: mcp-server-finanassets
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:xxx}
      chat:
        options:
          model: claude-opus-4-5


twelvedata:
  api-key: ${TWELVEDATA_API_KEY}