server:
  port: 8081

spring:
  application:
    name: trader-mcp-tools
  ai:
    mcp:
      server:
        name: trader-mcp-tools
        version: 1.0.0
        type: SYNC
        # By default, endpoints are at /sse and /mcp/message


twelvedata:
  api-key: ${TWELVEDATA_API_KEY}