-- -----------------------------------------------------------------------------
-- Drop table if exists (H2 safe syntax)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS portfolio_asset;

-- -----------------------------------------------------------------------------
-- portfolio_asset table
-- -----------------------------------------------------------------------------
CREATE TABLE portfolio_asset (
                          id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          symbol              VARCHAR(11)     NOT NULL,
                          name                VARCHAR(25),
                          quantity            INT,
                          purchasePrice       BIGINT,
                          currency            VARCHAR(1)      NOT NULL
    -- Constraints
                          CONSTRAINT uq_asset_id
                              UNIQUE (id)

);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------
CREATE UNIQUE INDEX idx_portfolio_asset_id
    ON portfolio_asset (id);