spring:
  application:
    name: trader
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

      mcp:
        client:
          enabled: true
          streamable-http:
            connections:
              financial-server:
                url: "http://localhost:8081"