spring:
  application:
    name: trader

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_ID:service-a}
            client-secret: ${OAUTH2_CLIENT_SECRET:}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
        provider:
          keycloak:
            token-uri: ${OAUTH2_TOKEN_URI:http://keycloak:8080/auth/realms/demo/protocol/openid-connect/token}
            issuer-uri: ${OAUTH2_ISSUER_URI:http://keycloak:8080/auth/realms/demo}


  ai:
    mcp:
      client:
        enabled: true
        streamable-http:
          connections:
            financial-server:
              url: "http://localhost:8081"

embabel:
  agent:
    platform:
      models:
        openai:
          api-key: ${OPENAI_API_KEY}
    logging:
      personality: starwars
  models:
    default-llm: claude-sonnet-4-6
    llms:
      reviewer: claude-opus-4-6