spring:
  application:
    name: trader
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:xxx}
      chat:
        options:
          model: claude-opus-4-5
      mcp:
        client:
          type: SYNC
          sse:
            connections:
              twelvedata-service:
                url: "http://your-remote-server:8080/mcp/sse"