plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.agilesolutions'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenLocal()
	mavenCentral()
	maven { url = 'https://repo.spring.io/milestone' }
	maven { url = 'https://repo.spring.io/snapshot' }
	maven { url = uri("https://repo.embabel.com/artifactory/libs-snapshot") }
}
ext {
	set('springAiVersion', "2.0.0-RC1")
}

dependencies {
	implementation project(':trader-common')
	implementation project(':trader-mcp-tools')

	// Bill of Materials
	implementation platform("org.springframework.ai:spring-ai-bom:1.1.4")
	implementation platform("io.modelcontextprotocol.sdk:mcp-bom:0.8.1")
	implementation platform("com.embabel.agent:embabel-agent-experimental-bom:0.3.5-SNAPSHOT")

	// Core and MCP Client dependencies
	implementation 'com.embabel.agent:embabel-agent-starter:0.4.0'
	implementation 'com.embabel.agent:embabel-agent-starter-shell:0.4.0'
	implementation 'com.embabel.agent:embabel-agent-starter-openai:0.4.0'

	implementation 'org.springframework.ai:spring-ai-starter-mcp-client-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	// Choose one LLM provider
	implementation 'org.springframework.ai:spring-ai-starter-model-openai'
	// OR
	// implementation 'org.springframework.ai:spring-ai-starter-model-anthropic'
	// OR
	// implementation 'org.springframework.ai:spring-ai-starter-model-azure-openai'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
